### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9mdW5jaW9uYXJpbyI6MSwiZXhwaXJhX2VtIjoiMjAyNC0wNC0wMVQyMjo0MTo0My4yNjk0NzIifQ.QmC273Jzy_5w20TWpjF8cvmQOj1KREB9rZdnKyRSqO0

### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9mdW5jaW9uYXJpbyI6MSwiZXhwaXJhX2VtIjoiMjAyNC0wNC0wMVQyMjo0MTo0My4yNjk0NzIifQ.QmC273Jzy_5w20TWpjF8cvmQOj1KREB9rZdnKyRSqO0

### Verbo POST – adicionar
POST http://localhost:8000/cliente/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9mdW5jaW9uYXJpbyI6MSwiZXhwaXJhX2VtIjoiMjAyNC0wNC0wMVQyMjo0MTo0My4yNjk0NzIifQ.QmC273Jzy_5w20TWpjF8cvmQOj1KREB9rZdnKyRSqO0
{
  "nome" : "Abc da Silva",
  "cpf" : "01923874656",
  "telefone" : "49988234567",
}

### Verbo PUT – atualiza
PUT http://localhost:8000/cliente/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9mdW5jaW9uYXJpbyI6MSwiZXhwaXJhX2VtIjoiMjAyNC0wNC0wMVQyMjo0MTo0My4yNjk0NzIifQ.QmC273Jzy_5w20TWpjF8cvmQOj1KREB9rZdnKyRSqO0
{
  "nome" : "Bolinhas dos Testes",
  "cpf" : "12345678909",
  "telefone" : "49898989",
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/cliente/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9mdW5jaW9uYXJpbyI6MSwiZXhwaXJhX2VtIjoiMjAyNC0wNC0wMVQyMjo0MTo0My4yNjk0NzIifQ.QmC273Jzy_5w20TWpjF8cvmQOj1KREB9rZdnKyRSqO0